### ISSUE TITLE
Which environment variable I need to set in production

### ISSUE THREAD

**Issue by shlomiLan** [edskeizer/ionic-environment-starter#1]
When I deploy my app in which environment variable I can use in order to set it as "Production"?

**Comment by edskeizer** [comment]
Hi shlomiLan,

You just can use the '--prod' parameter. E.g. 'ionic cordova build ios --prod'. 

Does that work for you?

**Comment by shlomiLan** [comment]
I'm deploying my code to Heroku and run it with `express` server. what is the best way for that?

**Comment by edskeizer** [comment]
Hi @shlomiLan, why would you want to deploy a Ionic app as a Node/Express server?

**Comment by shlomiLan** [comment]
I want to have a Web interface to my app in addition to the IOS and Android version. Is that make sense?

**Comment by shlomiLan** [comment]
I end up using [this](https://medium.com/@chaitanyamankala/adding-environment-for-ionic-2-3-projects-45ae9d50dcda) post, not sure that I even need `cross-env` because I'm setting the environment variables in the server itself. When I will `build` the app I will have set the env var locally as well but this can give me more flexibility.
